# Generated by Django 5.0.1 on 2024-03-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0002_hotel_gym_alter_hotel_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='type_of_room',
            new_name='type',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hotels',
            field=models.ManyToManyField(related_name='roomtypes', to='zomato.hotel'),
        ),
    ]
