# Generated by Django 5.0.1 on 2024-03-06 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0005_reservation_email_reservation_name_reservation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomato.roomtype'),
        ),
    ]
