# Generated by Django 5.0.1 on 2024-03-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0006_alter_reservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')]),
        ),
    ]
