# Generated by Django 5.0.1 on 2024-03-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0009_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type',
            field=models.CharField(max_length=5),
        ),
    ]
