# Generated by Django 5.0.1 on 2024-03-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0010_alter_reservation_phone_alter_roomtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
