# Generated by Django 5.0.1 on 2024-03-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0011_alter_reservation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
    ]
