# Generated by Django 5.0.1 on 2024-03-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0012_hotel_image_1_hotel_image_2_hotel_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
