# Generated by Django 5.0.1 on 2024-03-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0013_alter_hotel_image_1_alter_hotel_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
    ]
